#!/usr/bin/env python3
"""Editorial / Archive in Motion concept for Nora Sayyad.

Imported by build_options.py. The generated page lives at
opcoes/editorial/index.html.
"""

def concept_editorial():
    return r'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Nora Sayyad — Editorial / Archive in Motion</title>
<meta name="description" content="Editorial portfolio concept for Nora Sayyad, Finnish-Palestinian photographer and visual artist based in Helsinki.">
<meta name="robots" content="noindex">
<link rel="icon" href="/assets/favicon.svg" type="image/svg+xml">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600&family=Newsreader:opsz,wght@6..72,400;6..72,500&display=swap" rel="stylesheet">
<style>
:root{--paper:#f3f0e8;--ink:#111111;--blue:#17345f;--olive:#727454;--oxide:#a54a3f;--gray:#aaa69d;--line:rgba(17,17,17,.16);--white:#fbfaf6}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--paper);color:var(--ink);font:400 15px/1.55 "Manrope",system-ui,sans-serif}img{display:block;width:100%;height:auto}a{color:inherit;text-decoration:none}button{font:inherit}.wrap{width:min(1420px,calc(100% - 56px));margin:0 auto}.eyebrow{font-size:.68rem;letter-spacing:.16em;text-transform:uppercase}.serif{font-family:"Newsreader",Georgia,serif;font-weight:400}
.site-header{height:72px;display:flex;align-items:center;border-bottom:1px solid var(--line);background:rgba(243,240,232,.94);backdrop-filter:blur(12px);position:sticky;top:0;z-index:50}.site-header .wrap{display:flex;align-items:center;justify-content:space-between;gap:28px}.brand{font-family:"Newsreader",serif;font-size:1.25rem;letter-spacing:.08em;text-transform:uppercase}.nav{display:flex;align-items:center;gap:28px;font-size:.72rem}.nav a{position:relative}.nav a::after{content:"";position:absolute;left:0;right:100%;bottom:-5px;height:1px;background:currentColor;transition:.25s}.nav a:hover::after{right:0}.lang{display:flex;gap:10px;margin-left:10px;color:#666}.menu{display:none;border:0;background:none;font-size:1.2rem}
.hero{padding:22px 0 0}.hero-media{height:min(72vh,760px);position:relative;overflow:hidden;background:#20201e}.hero-media img{height:100%;object-fit:cover;object-position:center 42%;filter:saturate(.86) contrast(1.02)}.hero-media::after{content:"";position:absolute;inset:0;background:linear-gradient(90deg,rgba(10,10,10,.64) 0%,rgba(10,10,10,.22) 42%,rgba(10,10,10,.03) 70%)}.hero-copy{position:absolute;z-index:2;left:clamp(26px,4vw,68px);top:50%;transform:translateY(-50%);width:min(500px,42vw);color:white}.hero-copy h1{font-size:clamp(4rem,7vw,7.6rem);line-height:.78;letter-spacing:-.055em;margin:0 0 18px}.hero-copy p{font-size:clamp(.94rem,1.25vw,1.1rem);max-width:34rem;margin:0 0 22px}.hero-quote{position:absolute;z-index:2;right:5%;bottom:11%;width:min(310px,28vw);color:#fff;font-family:"Newsreader",serif;font-style:italic;font-size:clamp(1.05rem,1.7vw,1.5rem);line-height:1.2;text-align:right}.btn{display:inline-flex;align-items:center;gap:12px;border:1px solid currentColor;padding:11px 15px;font-size:.68rem;letter-spacing:.08em;text-transform:uppercase;transition:.2s}.btn:hover{background:var(--ink);color:var(--paper)}.hero .btn:hover{background:white;color:#111}.hero-index{position:absolute;z-index:2;bottom:22px;left:50%;transform:translateX(-50%);display:flex;gap:8px;color:white;font-size:.66rem}
section{padding:74px 0;border-bottom:1px solid var(--line)}.section-head{display:flex;align-items:end;justify-content:space-between;gap:18px;margin-bottom:24px}.section-head h2{font-family:"Newsreader",serif;font-size:clamp(2rem,3.2vw,3.2rem);font-weight:400;margin:0;line-height:.95}.section-head a{font-size:.7rem;letter-spacing:.11em;text-transform:uppercase}
.projects{display:grid;grid-template-columns:1.15fr .95fr .95fr .95fr;gap:14px}.project{display:block}.project .image{overflow:hidden;background:#ddd8cc;aspect-ratio:4/5}.project:first-child .image{aspect-ratio:1.1/1}.project img{height:100%;object-fit:cover;transition:transform .55s ease,filter .4s}.project:hover img{transform:scale(1.025);filter:saturate(.9)}.project h3{font-family:"Newsreader",serif;font-weight:400;font-size:1.35rem;line-height:1.05;margin:12px 0 4px}.project .meta{font-size:.63rem;letter-spacing:.12em;text-transform:uppercase;color:#5d5b55}
.cred-strip{padding:30px 0}.cred-strip .wrap{display:grid;grid-template-columns:220px 1fr;gap:26px;align-items:center}.credentials{display:grid;grid-template-columns:repeat(6,1fr);gap:24px;align-items:center}.credentials span{font-family:"Newsreader",serif;font-size:1.05rem;line-height:1.05;text-align:center}
.current-grid{display:grid;grid-template-columns:1.05fr 1fr 1fr;gap:38px;align-items:start}.current-image{aspect-ratio:4/3;overflow:hidden;background:#d8d3c8}.current-image img{height:100%;object-fit:cover}.current-main h2{font-family:"Newsreader",serif;font-weight:400;font-size:clamp(2.2rem,3.3vw,3.9rem);line-height:.92;margin:10px 0 18px}.current-main p{max-width:39rem}.news-card{border-top:1px solid var(--ink);padding-top:12px}.news-card h3{font-family:"Newsreader",serif;font-size:1.65rem;line-height:1.05;font-weight:400;margin:8px 0}.news-card p{color:#5d5b55}
.story-band{padding:0;border-bottom:0}.story-band .wrap{width:min(1500px,calc(100% - 28px));position:relative;height:min(66vh,700px);overflow:hidden;background:#222}.story-band img{height:100%;object-fit:cover}.story-band .wrap::after{content:"";position:absolute;inset:0;background:linear-gradient(90deg,rgba(10,10,10,.12),rgba(10,10,10,.62))}.story-quote{position:absolute;z-index:2;right:8%;top:50%;transform:translateY(-50%);max-width:560px;color:white;font-family:"Newsreader",serif;font-size:clamp(2rem,4vw,4.3rem);line-height:.95}.story-quote small{display:block;margin-top:24px;font-family:"Manrope",sans-serif;font-size:.67rem;letter-spacing:.14em;text-transform:uppercase}
.about-grid{display:grid;grid-template-columns:.72fr 1.28fr;gap:70px;align-items:start}.about-image{aspect-ratio:4/5;background:linear-gradient(135deg,#d9d2c3,#bcb4a3);display:grid;place-items:center;color:#5e5a50;text-align:center;padding:30px}.about-copy h2{font-family:"Newsreader",serif;font-size:clamp(2.6rem,5vw,5.5rem);line-height:.88;font-weight:400;margin:0 0 26px}.about-copy .lead{font-family:"Newsreader",serif;font-size:1.5rem;line-height:1.2;max-width:760px}.about-cols{display:grid;grid-template-columns:1fr 1fr;gap:34px;margin-top:34px}.about-cols p{color:#55524c;margin:0}
.commissions{background:var(--blue);color:white}.commission-grid{display:grid;grid-template-columns:1.1fr .9fr;gap:50px;align-items:end}.commissions h2{font-family:"Newsreader",serif;font-weight:400;font-size:clamp(3rem,6vw,7rem);line-height:.83;margin:0}.commissions p{max-width:520px;font-size:1.05rem}.commissions .btn:hover{background:white;color:var(--blue)}
.footer{padding:34px 0 44px}.footer .wrap{display:flex;justify-content:space-between;gap:20px;flex-wrap:wrap}.footer p,.footer a{font-size:.74rem}.switch{position:fixed;right:12px;bottom:12px;z-index:90;background:#111;color:#fff;font:500 13px/1 system-ui,sans-serif;padding:10px 14px;border-radius:999px;text-decoration:none;box-shadow:0 4px 18px rgba(0,0,0,.25)}
@media(max-width:950px){.wrap{width:min(100% - 28px,1420px)}.site-header{height:62px}.nav{display:none}.menu{display:block}.hero{padding-top:12px}.hero-media{height:76vh}.hero-copy{left:24px;right:24px;width:auto;top:auto;bottom:70px;transform:none}.hero-copy h1{font-size:clamp(3.3rem,17vw,6rem)}.hero-quote{display:none}.projects{grid-template-columns:1fr 1fr}.project:first-child .image{aspect-ratio:4/5}.cred-strip .wrap{grid-template-columns:1fr}.credentials{grid-template-columns:repeat(2,1fr);gap:18px}.current-grid{grid-template-columns:1fr}.about-grid{grid-template-columns:1fr}.about-image{aspect-ratio:16/9}.commission-grid{grid-template-columns:1fr}}
@media(max-width:560px){body{font-size:14px}section{padding:52px 0}.hero-media{height:72vh}.hero-copy p{max-width:30rem}.projects{grid-template-columns:1fr}.project .image,.project:first-child .image{aspect-ratio:4/5}.section-head{align-items:start}.section-head h2{font-size:2.4rem}.credentials{grid-template-columns:1fr 1fr}.about-cols{grid-template-columns:1fr}.story-band .wrap{height:66vh}.story-quote{left:24px;right:24px;top:auto;bottom:30px;transform:none}}
</style>
</head>
<body>
<header class="site-header"><div class="wrap"><a class="brand" href="/opcoes/editorial/">Nora Sayyad</a><nav class="nav" aria-label="Main"><a href="/work/">Work</a><a href="/news/">Current</a><a href="/services/">Commissions</a><a href="/about/">About</a><a href="/contact/">Contact</a><span class="lang">EN&nbsp;&nbsp; FI</span></nav><button class="menu" type="button" aria-label="Open menu">☰</button></div></header>
<main>
<section class="hero" style="padding-bottom:0;border-bottom:0"><div class="wrap"><div class="hero-media"><img src="https://images.squarespace-cdn.com/content/v1/6818f37ce1899b43f8d64046/01cbc07a-6516-4597-8a09-219c1fb966db/4W7A3479.jpg?format=2500w" alt="A woman in a headscarf in warm evening light"><div class="hero-copy"><h1 class="serif">NORA<br>SAYYAD</h1><p>Finnish-Palestinian photographer, artist and visual reporter based in Helsinki. Working across documentary and poetic storytelling.</p><a class="btn" href="/work/">Explore work <span>→</span></a></div><blockquote class="hero-quote">“Stories, people and places that refuse to be forgotten.”</blockquote><div class="hero-index">01 / 04 &nbsp;&nbsp; ← &nbsp; →</div></div></div></section>
<section><div class="wrap"><div class="section-head"><h2>Selected projects</h2><a href="/work/">View all projects →</a></div><div class="projects">
<a class="project" href="/work/from-arrival-to-belonging/"><div class="image"><img src="https://images.squarespace-cdn.com/content/v1/6818f37ce1899b43f8d64046/a4a39869-0b02-4ffe-9865-0f443df7fdcc/nora_sayyad_UKJ1.jpg?format=1500w" alt="Portrait of a young woman in red, against a blue backdrop"></div><h3>From Arrival to Belonging?</h3><div class="meta">2025–2026 · Documentary</div></a>
<a class="project" href="/work/notes-of-resistance/"><div class="image"><img src="https://images.squarespace-cdn.com/content/v1/6818f37ce1899b43f8d64046/8a22cfb8-4135-473c-a21f-8d0319b9d695/_A2A4998.jpg?format=1500w" alt="A Palestinian flag held high over a street demonstration"></div><h3>Notes of Resistance</h3><div class="meta">2020–2024 · Documentary</div></a>
<a class="project" href="/work/parfyymin-tuulahdus/"><div class="image"><img src="https://images.squarespace-cdn.com/content/v1/6818f37ce1899b43f8d64046/b6e1baa5-1f89-4868-8972-ec0759a4b5b7/Parfyymin_tuulahdus_still_leben_grain_valo_01+%282%29.jpg?format=1500w" alt="Still life of perfume bottles on a dark, blue-lit surface"></div><h3>Parfyymin tuulahdus</h3><div class="meta">Conceptual</div></a>
<a class="project" href="/work/portraits/"><div class="image"><img src="https://images.squarespace-cdn.com/content/v1/6818f37ce1899b43f8d64046/0d7e0888-94e5-4956-9e26-70b1e8888d7e/249A6278.jpg?format=1500w" alt="A woman in an orange jacket, her hair caught in motion"></div><h3>Portraits</h3><div class="meta">Ongoing · Portraiture</div></a>
</div></div></section>
<section class="cred-strip"><div class="wrap"><div class="eyebrow">Selected clients & publications</div><div class="credentials"><span>The Washington Post</span><span>The Times</span><span>Helsinki City Museum</span><span>Finnish Museum of Photography</span><span>Plan International</span><span>Startup Refugees</span></div></div></section>
<section><div class="wrap"><div class="section-head"><h2>Current</h2><a href="/news/">Exhibitions & news →</a></div><div class="current-grid"><div class="current-image"><img src="https://images.squarespace-cdn.com/content/v1/6818f37ce1899b43f8d64046/13b64272-dd16-4ef4-8309-80a4ccec441c/_A2A0233_SRGB.jpg?format=1500w" alt="A protester wrapped in a keffiyeh stands at a building entrance"></div><div class="current-main"><div class="eyebrow">Exhibition · 2025–2026</div><h2>The Lost Paintings: A Prelude to Return</h2><p>A travelling group exhibition moving through Canada, the United States, Northern Ireland and the United Kingdom, including Nora Sayyad’s work <em>Utopia</em>.</p><a class="btn" href="/news/">View details →</a></div><article class="news-card"><div class="eyebrow">In the news</div><h3>How is “happiness” measured around the world?</h3><p>Selected editorial work photographed for The Washington Post in Finland.</p><a class="eyebrow" href="/news/">Read selected press →</a></article></div></div></section>
<section class="story-band"><div class="wrap"><img src="https://images.squarespace-cdn.com/content/v1/6818f37ce1899b43f8d64046/1746530662510-8H15BYD3FAAEB25P2SB5/ELY_KANSI_01_INSTAGRAM_valoisampi.jpg?format=2500w" alt="A woman and a man stand back to back on a hillside, in black and white"><blockquote class="story-quote">Photography can become a space for memory, dialogue and self-determination.<small>Nora Sayyad · visual practice</small></blockquote></div></section>
<section><div class="wrap about-grid"><div class="about-image"><div><div class="eyebrow">Portrait placeholder</div><p>Professional portrait of Nora to be selected by Nora before publication.</p></div></div><div class="about-copy"><div class="eyebrow">About</div><h2>Documentary, poetic and conceptual.</h2><p class="lead">Nora Sayyad is a Finnish-Palestinian photographer, artist and visual reporter whose experimental lens moves between documentary and fictional storytelling.</p><div class="about-cols"><p>Her practice explores belonging, memory, diaspora, representation and the politics of looking.</p><p>Based in Helsinki, she works across photography, visual reporting, writing, teaching and public speaking.</p></div><p style="margin-top:30px"><a class="btn" href="/about/">Biography & CV →</a></p></div></div></section>
<section class="commissions"><div class="wrap commission-grid"><h2>Commissions<br>& editorial.</h2><div><p>Available for editorial, institutional and selected commissioned work. Studio and location photography, visual reporting and portraiture.</p><p><a class="btn" href="/contact/">Discuss a project →</a></p></div></div></section>
</main>
<footer class="footer"><div class="wrap"><p>© Nora Sayyad · Helsinki, Finland</p><p><a href="mailto:ellinorasayyad@gmail.com">ellinorasayyad@gmail.com</a> · <a href="https://www.instagram.com/norasayyad/">Instagram</a></p></div></footer>
<a class="switch" href="/opcoes/">← Todas as opções</a>
</body>
</html>'''
